name: k8s extract images
description: Attempts to extract images from a file containing Kubernetes manifests.
inputs:
  manifests-file:
    description: The file containing the Kubernetes manifests to extract images from.
    required: true
  format:
    description: >-
      The format that images will be output in.
      Currently json and newline are supported, with newline being the default.
    required: true
    default: newline
outputs:
  images:
    description: JSON-formatted list of images discovered.
runs:
  using: docker
  image: Dockerfile
  args:
    - --format
    - ${{ inputs.format }}
    - ${{ inputs.manifests-file }}
