name: Helm template
description: >-
  Templates the manifests for a Helm chart.
inputs:
  repository:
    description: The Helm repository containing the chart.
    required: true
  chart:
    description: The name of the chart.
    required: true
  version:
    description: The version of the chart to use.
    required: true
  values:
    description: The values to use when templating the chart.
    default: "{}"
  release-name:
    description: >-
      The release name to use when templating the chart.
      Defaults to the chart name if not given.
    default: ""
  release-namespace:
    description: >-
      The release namespace to use when templating the chart.
      Defaults to 'default' if not given.
    default: default
outputs:
  manifests:
    description: The templated manifests.
    value: ${{ steps.helm-template.outputs.manifests }}
runs:
  using: composite
  steps:
    - name: Template manifests using Helm
      id: helm-template
      shell: bash
      run: |
        echo "manifests<<EOF" >> $GITHUB_OUTPUT
        helm template \
          "$RELEASE_NAME" \
          "$CHART_NAME" \
          --repo "$CHART_REPO" \
          --version "$CHART_VERSION" \
          --values - \
          --namespace "$RELEASE_NAMESPACE" \
          --skip-tests \
          <<< "$CHART_VALUES" \
          >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      env:
        CHART_REPO: ${{ inputs.repository }}
        CHART_NAME: ${{ inputs.chart }}
        CHART_VERSION: ${{ inputs.version }}
        CHART_VALUES: ${{ inputs.values }}
        RELEASE_NAME: ${{ inputs.release-name || inputs.chart }}
        RELEASE_NAMESPACE: ${{ inputs.release-namespace }}
