name: Build and push multi-architecture Docker image
description: >
  Builds and pushes a multi-architecture Docker image using QEMU and buildx.
inputs:
  cache-key:
    description: Cache key for the image, used to preserve Docker layer cache.
    required: true
  build-args:
    description: List of build-time variables
    required: false
  context:
    description: Directory to use for the build context
    required: false
  file:
    description: Path to the Dockerfile
    required: false
  labels:
    description: List of metadata for an image
    required: false
  platforms:
    description: List of target platforms for build
    required: false
  pull:
    description: Always attempt to pull a newer version of the image
    required: false
    default: 'false'
  push:
    description: Whether or not to push the resulting image
    required: false
    default: 'false'
  tags:
    description: List of tags
    required: false
  sign_image:
    description: If true cosign is used to sign the image
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    # Ideas from:
    # https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml
    # Install the cosign tool except on PR
    # https://github.com/sigstore/cosign-installer
    - name: Install cosign
      if: github.event_name != 'pull_request'
      uses: sigstore/cosign-installer@6e04d228eb30da1757ee4e1dd75a0ec73a653e06 #v3.1.1
      with:
        cosign-release: 'v2.1.1'

    # Set up BuildKit Docker container builder to be able to build
    # multi-platform images and export cache
    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

    - name: Set up Docker layer caching
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ inputs.cache-key }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ inputs.cache-key }}-

    - name: Build and push image
      id: build-and-push
      uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
      with:
        build-args: ${{ inputs.build-args }}
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        labels: ${{ inputs.labels }}
        platforms: ${{ inputs.platforms }}
        pull: ${{ inputs.pull }}
        push: ${{ inputs.push }}
        tags: ${{ inputs.tags }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@2b6a709cf9c4025c5438138008beaddbb02086f0
      with:
        image-ref: ${{ inputs.tags }}
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

    # Sign the resulting Docker image digest except on PRs.
    # This will only write to the public Rekor transparency log when the Docker
    # repository is public to avoid leaking data.  If you would like to publish
    # transparency data even for private images, pass --force to cosign below.
    # https://github.com/sigstore/cosign
    - name: Sign the published Docker image
      if: ${{ inputs.sign_image == 'true' }}
      env:
        # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
        TAGS: ${{ inputs.tags }}
        DIGEST: ${{ steps.build-and-push.outputs.digest }}
      # This step uses the identity token to provision an ephemeral certificate
      # against the sigstore community Fulcio instance.
      shell: bash
      run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    # https://github.com/docker/buildx/pull/535
    - name: Move cache
      shell: bash
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
